apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mockapp-secrets
  namespace: default
spec:
  secretStoreRef:
    name: mockapp-secret-store
    kind: SecretStore
  target:
    name: mockapp-secrets
    deletionPolicy: "Delete"
  data:
    - secretKey: SECRET_TEST
      remoteRef:
        key: SECRET_TEST
        version: latest
