apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mockapp-secrets
  namespace: fulfillment
spec:
  secretStoreRef:
    name: mockapp-secret-store
    kind: SecretStore
  target:
    name: mockapp-secrets
    deletionPolicy: "Delete"
  data:
    # - secretKey: FULFILLMENT_TAX_API_MONGO_DB_URI
    #   remoteRef:
    #     key: FULFILLMENT_TAX_API_MONGO_DB_URI
    #     version: latest
    # - secretKey: FULFILLMENT_TAX_API_RABBITMQ_USERNAME
    #   remoteRef:
    #     key: FULFILLMENT_TAX_API_RABBITMQ_USERNAME
    #     version: latest
    # - secretKey: FULFILLMENT_TAX_API_RABBITMQ_PASSWORD
    #   remoteRef:
    #     key: FULFILLMENT_TAX_API_RABBITMQ_PASSWORD
    #     version: latest