apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mockapp-secrets
  namespace: default
spec:
  secretStoreRef:
    name: mockapp-secret-store
    kind: SecretStore
  target:
    name: mockapp-secrets
    deletionPolicy: "Delete"
  data:
    - secretKey: SECRET_TEST
      remoteRef:
        key: SECRET_TEST
        version: latest
    # - secretKey: FULFILLMENT_TAX_API_RABBITMQ_USERNAME
    #   remoteRef:
    #     key: FULFILLMENT_TAX_API_RABBITMQ_USERNAME
    #     version: latest
    # - secretKey: FULFILLMENT_TAX_API_RABBITMQ_PASSWORD
    #   remoteRef:
    #     key: FULFILLMENT_TAX_API_RABBITMQ_PASSWORD
    #     version: latest