apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fulfillment
resources:
  - deployment.yaml
  - services.yaml
  - external-secret.yaml
  - config-map.yaml
  - secret-store.yaml
  - hpa.yaml
images:
  - name: us-central1-docker.pkg.dev/playground-s-11-d8aac915/mockapp-repo/mockapp
    newTag: 1602349-92
