apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: mockapp-secret-store
  namespace: fulfillment
spec:
  controller: fulfillment
  provider:
    gcpsm:
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterProjectID: playground-s-11-d8aac915
          clusterName: example-gke
          serviceAccountRef:
            name: external-secrets
      projectID: playground-s-11-d8aac915