apiVersion: v1
kind: Service
metadata:
  name: mockapp-svc
  labels:
    app: mockapp
    env: test
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: mockapp
    env: test
  type: LoadBalancer
