#Name of the workflow
name: Testing for labs
on: 
  workflow_call:
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:
  clean_branch:
    name: Cleaning generated branch
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 #Gets the github files 
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN_FOR_GITHUB }}
      - run: echo ${{ github.head_ref }}
      - run: |
          git push origin --delete ${{ github.head_ref }}

    
